// Register user

export const REGISTER_START = "REGISTER_START"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILURE = "REGISTER_FAILURE"

// lOGIN ACTION

export const LOGIN_START = "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

// RECIPES FETCH

export const FETCH_RECIPES_START = "FETCH_RECIPES_START"
export const FETCH_RECIPES_SUCCESS = "FETCH_RECIPES_SUCCESS"
export const FETCH_RECIPES_FAILURE = "FETCH_RECIPES_FAILURE"

//ADD RECOPE

export const ADD_RECIPE_START = "ADD_RECIPE_START"
export const ADD_RECIPES_SUCESS = "ADD_RECIPES_SUCCESS"
export const ADD_RECIPES_FAILURE = "ADD_RECIPES_FAILURE"

//GET RECIPE BY USER

export const FETCH_RECIPESBYUSER_START = "FETCH_RECIPESBYUSER_START"
export const FETCH_RECIPESBYUSER_SUCCESS = "FETCH_RECIPESBYUSER_SUCCESS"
export const FETCH_RECIPESBYUSER_FAILURE = "FETCH_RECIPESBYUSER_FAILURE"

//DELETE ACTION

export const DELETE_RECIPE_START = "DELETE_RECIPE_START"
export const DELETE_RECIPE_SUCCESS = "DELETE_RECIPE_SUCCESS"
export const DELETE_RECIPE_FAILURE = "DELETE_RECIPE_FAILURE"

//UPDATE ACTIONS

export const UPDATE_RECIPE_START = "UPDATE_RECIPE_START"
export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS"
export const UPDATE_RECIPE_FAILURE = "UPDATE_RECIPE_FAILURE"

export const ADD_RECIPE_EDIT = "ADD_RECIPE_EDIT"
